// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import '../model/aluno.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(1, 2075948353597425075),
      name: 'Aluno',
      lastPropertyId: const IdUid(6, 8762752047021668548),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 2892948863729272146),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 3055495177477959339),
            name: 'nome',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 89257673160812204),
            name: 'sobrenome',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 996073989356857728),
            name: 'sexo',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 8044462405229340954),
            name: 'idade',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(6, 8762752047021668548),
            name: 'presente',
            type: 1,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Shortcut for [Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [Store.new] for an explanation of all parameters.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// Returns the ObjectBox model definition for this project for use with
/// [Store.new].
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(1, 2075948353597425075),
      lastIndexId: const IdUid(0, 0),
      lastRelationId: const IdUid(0, 0),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    Aluno: EntityDefinition<Aluno>(
        model: _entities[0],
        toOneRelations: (Aluno object) => [],
        toManyRelations: (Aluno object) => {},
        getId: (Aluno object) => object.id,
        setId: (Aluno object, int id) {
          object.id = id;
        },
        objectToFB: (Aluno object, fb.Builder fbb) {
          final nomeOffset = fbb.writeString(object.nome);
          final sobrenomeOffset = fbb.writeString(object.sobrenome);
          final sexoOffset = fbb.writeString(object.sexo);
          fbb.startTable(7);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, nomeOffset);
          fbb.addOffset(2, sobrenomeOffset);
          fbb.addOffset(3, sexoOffset);
          fbb.addInt64(4, object.idade);
          fbb.addBool(5, object.presente);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final nomeParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final sobrenomeParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final sexoParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 10, '');
          final idadeParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0);
          final object = Aluno(nomeParam, sobrenomeParam, sexoParam, idadeParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..presente =
                const fb.BoolReader().vTableGet(buffer, rootOffset, 14, false);

          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [Aluno] entity fields to define ObjectBox queries.
class Aluno_ {
  /// see [Aluno.id]
  static final id = QueryIntegerProperty<Aluno>(_entities[0].properties[0]);

  /// see [Aluno.nome]
  static final nome = QueryStringProperty<Aluno>(_entities[0].properties[1]);

  /// see [Aluno.sobrenome]
  static final sobrenome =
      QueryStringProperty<Aluno>(_entities[0].properties[2]);

  /// see [Aluno.sexo]
  static final sexo = QueryStringProperty<Aluno>(_entities[0].properties[3]);

  /// see [Aluno.idade]
  static final idade = QueryIntegerProperty<Aluno>(_entities[0].properties[4]);

  /// see [Aluno.presente]
  static final presente =
      QueryBooleanProperty<Aluno>(_entities[0].properties[5]);
}
